package jmd.dao;

import jmd.po.Task;
import jmd.po.TaskExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface TaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated
     */
    @Delete({
        "delete from task",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated
     */
    @Insert({
        "insert into task (id, task_type_id, ",
        "project, code, task_short_name, ",
        "task_name, status, ",
        "start_date, cut_off_date, ",
        "priority, important, ",
        "user_id, field_1, ",
        "field_2, field_3)",
        "values (#{id,jdbcType=INTEGER}, #{taskTypeId,jdbcType=INTEGER}, ",
        "#{project,jdbcType=VARCHAR}, #{code,jdbcType=VARCHAR}, #{taskShortName,jdbcType=VARCHAR}, ",
        "#{taskName,jdbcType=VARCHAR}, #{status,jdbcType=INTEGER}, ",
        "#{startDate,jdbcType=TIMESTAMP}, #{cutOffDate,jdbcType=TIMESTAMP}, ",
        "#{priority,jdbcType=INTEGER}, #{important,jdbcType=VARCHAR}, ",
        "#{userId,jdbcType=VARCHAR}, #{field1,jdbcType=VARCHAR}, ",
        "#{field2,jdbcType=VARCHAR}, #{field3,jdbcType=VARCHAR})"
    })
    int insert(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated
     */
    int insertSelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated
     */
    List<Task> selectByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, task_type_id, project, code, task_short_name, task_name, status, start_date, ",
        "cut_off_date, priority, important, user_id, field_1, field_2, field_3",
        "from task",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("jmd.dao.TaskMapper.BaseResultMap")
    Task selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated
     */
    @Update({
        "update task",
        "set task_type_id = #{taskTypeId,jdbcType=INTEGER},",
          "project = #{project,jdbcType=VARCHAR},",
          "code = #{code,jdbcType=VARCHAR},",
          "task_short_name = #{taskShortName,jdbcType=VARCHAR},",
          "task_name = #{taskName,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "start_date = #{startDate,jdbcType=TIMESTAMP},",
          "cut_off_date = #{cutOffDate,jdbcType=TIMESTAMP},",
          "priority = #{priority,jdbcType=INTEGER},",
          "important = #{important,jdbcType=VARCHAR},",
          "user_id = #{userId,jdbcType=VARCHAR},",
          "field_1 = #{field1,jdbcType=VARCHAR},",
          "field_2 = #{field2,jdbcType=VARCHAR},",
          "field_3 = #{field3,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Task record);
}