package jmd.po;

public class TaskType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_type.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_type.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_type.color
     *
     * @mbg.generated
     */
    private String color;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_type
     *
     * @mbg.generated
     */
    public TaskType(Integer id, String name, String color) {
        this.id = id;
        this.name = name;
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_type.id
     *
     * @return the value of task_type.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_type.name
     *
     * @return the value of task_type.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_type.color
     *
     * @return the value of task_type.color
     *
     * @mbg.generated
     */
    public String getColor() {
        return color;
    }
}